import { useEffect, useState } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { supabase } from '../../lib/supabase';
type Media = { id: string; media_type: string; object_path: string; visibility: string };
const labels: Record<string, string> = { headshot: 'Портрет', gallery: 'Фото', showreel: 'Шоурил', video_intro: 'Видеовизитка', self_tape: 'Самопроба', audio: 'Аудио', model_digitals: 'Digitals / естественные фото', model_portfolio: 'Модельное портфолио', model_walk: 'Проходка / runway video' };
export function ProfileMedia({ userId, editable = false }: { userId: string; editable?: boolean }) {
  const { user } = useAuth();
  const [rows, setRows] = useState<Media[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  const [opened, setOpened] = useState<{ url: string; type: string; expires: number } | null>(null);
  useEffect(() => { let stale = false; setRows([]); setOpened(null); setError(''); void (async () => { try { const r = await supabase.from('profile_media').select('id,media_type,object_path,visibility').eq('user_id', userId).order('created_at', { ascending: false }).limit(24); if (r.error) throw r.error; if (!stale) setRows(r.data || []); } catch { if (!stale) setError('Не удалось загрузить медиа.'); } })(); return () => { stale = true; }; }, [userId, user?.id, revision]);
  useEffect(() => { if (!opened) return; const timer = setTimeout(() => setOpened(null), Math.max(0, opened.expires - Date.now())); return () => clearTimeout(timer); }, [opened]);
  const open = async (row: Media) => { setError(''); setOpened(null); try { const r = await supabase.storage.from('profile-media').createSignedUrl(row.object_path, 60); if (r.error) throw r.error; setOpened({ url: r.data.signedUrl, type: row.media_type, expires: Date.now() + 60000 }); } catch { setError('Файл недоступен или право просмотра изменилось.'); } };
  return <section className="surface p-5 space-y-4"><h2 className="font-semibold">Медиа с контролем доступа</h2>{error && <p role="alert">{error}</p>}{rows.map(row => <div key={row.id} className="flex flex-wrap gap-3 items-center"><span>{labels[row.media_type]}{editable ? ` · ${row.visibility}` : ''}</span><button className="text-emerald-500" onClick={() => void open(row)}>Открыть файл</button>{editable && <select aria-label={`Видимость ${labels[row.media_type]} ${row.id}`} className="input-field !w-auto" disabled={busy || ['application_context', 'project_context'].includes(row.visibility)} value={row.visibility} onChange={e => { const visibility = e.target.value; setBusy(true); setError(''); void (async () => { try { const r = await supabase.from('profile_media').update({ visibility }).eq('id', row.id).select('id').single(); if (r.error) throw r.error; setRevision(n => n + 1); } catch { setError('Видимость не сохранена.'); } finally { setBusy(false); } })(); }}><option value="private">Только я</option><option value="members">Участники</option><option value="public">Публично</option>{['application_context', 'project_context'].includes(row.visibility) && <option value={row.visibility}>Рабочий контекст</option>}</select>}</div>)}
    {opened && (opened.type === 'audio' ? <audio controls src={opened.url} /> : ['headshot', 'gallery', 'model_digitals', 'model_portfolio'].includes(opened.type) ? <img src={opened.url} alt="Медиа профиля" className="max-h-96 object-contain" /> : <video controls src={opened.url} className="max-h-96 w-full" />)}
    {editable && <form className="space-y-3" onSubmit={e => { e.preventDefault(); if (!user || user.id !== userId) return; const form = e.currentTarget; const d = new FormData(form); const file = d.get('file'); if (!(file instanceof File) || !file.size || file.size > 50 * 1024 * 1024 || !/^(image\/(jpeg|png|webp)|video\/(mp4|webm)|audio\/(mpeg|wav|ogg))$/.test(file.type)) { setError('Выберите JPG, PNG, WebP, MP4, WebM, MP3, WAV или OGG до 50 МБ.'); return; }
      setBusy(true); setError(''); void (async () => { const objectPath = `${userId}/${crypto.randomUUID()}`; try {
        const metadata = await supabase.from('profile_media').insert({ media_type: d.get('type'), object_path: objectPath, visibility: 'private', model_angle: d.get('type') === 'model_digitals' ? d.get('angle') || null : null }).select('id').single(); if (metadata.error) throw metadata.error;
        const upload = await supabase.storage.from('profile-media').upload(objectPath, file, { contentType: file.type, upsert: false }); if (upload.error) { await supabase.from('profile_media').delete().eq('id', metadata.data.id); throw upload.error; }
        form.reset(); setRevision(n => n + 1);
      } catch { setError('Загрузка не завершена. Файл не был опубликован. Проверьте соединение и повторите.'); } finally { setBusy(false); } })(); }}>
      <label className="block">Тип медиа<select name="type" className="input-field">{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="block">Ракурс digitals<select name="angle" className="input-field"><option value="headshot_front">Лицо анфас</option><option value="profile">Профиль</option><option value="three_quarter">Три четверти</option><option value="full_front">Полный рост спереди</option><option value="full_side">Полный рост сбоку</option><option value="full_back">Полный рост сзади</option></select></label><input aria-label="Файл профиля" name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg" required /><button className="btn-secondary" disabled={busy}>{busy ? 'Загрузка…' : 'Загрузить приватно'}</button>
      <p className="text-xs text-txt-muted">Новый файл доступен только вам. Ссылка просмотра живёт 60 секунд. Старые публичные аватары не становятся закрытыми от изменения этих настроек. Рабочие самопробы передаются через отклик/проект, а не через публичную ссылку.</p>
    </form>}
  </section>;
}
