import { useEffect, useState } from 'react';
import { CompanyReferencePicker } from '../CompanyReferencePicker';
import { supabase } from '../../lib/supabase';
type Contact = { id: string; kind: string; value: string; visibility: string };
type Representative = { id: string; name: string; role_type: string; contact: string | null; territory?: string | null };
export function ProfileContacts({ userId, editable = false }: { userId: string; editable?: boolean }) {
  const [contacts, setContacts] = useState<Contact[]>([]); const [representatives, setRepresentatives] = useState<Representative[]>([]);
  const [revision, setRevision] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { let stale = false; setContacts([]); setRepresentatives([]); setError(''); void (async () => { try {
    const [c, r] = await Promise.all([supabase.from('profile_contacts').select('id,kind,value,visibility').eq('user_id', userId), supabase.rpc('person_representatives', { p_user: userId })]);
    if (c.error || r.error) throw new Error('load'); if (!stale) { setContacts(c.data || []); setRepresentatives(r.data || []); }
  } catch { if (!stale) setError('Не удалось загрузить контакты.'); } })(); return () => { stale = true; }; }, [userId, revision]);
  const save = async (table: string, values: Record<string, unknown>, form: HTMLFormElement) => {
    setBusy(true); setError(''); try { const r = await supabase.from(table).insert(values).select('id').single(); if (r.error) throw r.error; form.reset(); setRevision(n => n + 1); } catch { setError('Не сохранено. Контакт такого типа уже может существовать; сначала удалите старый.'); } finally { setBusy(false); }
  };
  const remove = async (table: string, id: string) => { setBusy(true); setError(''); try { const r = await supabase.from(table).delete().eq('id', id).select('id').single(); if (r.error) throw r.error; setRevision(n => n + 1); } catch { setError('Удаление не выполнено.'); } finally { setBusy(false); } };
  return <section className="surface p-5 space-y-4"><h2 className="font-semibold">Контакты и представительство</h2>{error && <p role="alert">{error}</p>}{contacts.map(c => <p key={c.id}>{c.kind === 'email' ? 'Почта' : 'Телефон'}: {c.value} {editable && <><small>({c.visibility})</small><button disabled={busy} className="ml-3" onClick={() => void remove('profile_contacts', c.id)}>Удалить</button></>}</p>)}{representatives.map(r => <div key={r.id}><strong>{r.name}</strong><p className="text-sm">{r.role_type}{r.territory ? ` · ${r.territory}` : ''}{r.contact ? ` · ${r.contact}` : ''}</p>{editable && <button disabled={busy} onClick={() => void remove('profile_representations', r.id)}>Удалить представителя</button>}</div>)}
    {editable && <><p className="text-xs text-txt-muted">Почта входа не публикуется. Добавьте отдельный контакт и явно выберите видимость.</p><form className="space-y-2" onSubmit={e => { e.preventDefault(); const f = e.currentTarget; const d = new FormData(f); void save('profile_contacts', { kind: d.get('kind'), value: d.get('value'), visibility: d.get('visibility') }, f); }}><select name="kind" aria-label="Тип контакта" className="input-field"><option value="email">Почта</option><option value="phone">Телефон</option></select><input name="value" aria-label="Контакт" className="input-field" required maxLength={254} /><Visibility name="visibility" /><button disabled={busy} className="btn-secondary">Добавить контакт</button></form>
      <form className="space-y-2 border-t border-line-soft pt-4" onSubmit={e => { e.preventDefault(); const f = e.currentTarget; const d = new FormData(f); void save('profile_representations', { organization_id: d.get('organization_id') || null, territory: d.get('territory') || null, starts_on: d.get('starts_on') || null, ends_on: d.get('ends_on') || null, name: d.get('name'), role_type: d.get('role_type'), contact: d.get('contact'), visibility: d.get('visibility'), contact_visibility: d.get('contact_visibility') }, f); }}><label className="block">Представитель<input name="name" className="input-field" required maxLength={160} /></label><label className="block">Роль<input name="role_type" className="input-field" defaultValue="Агент" maxLength={80} /></label><CompanyReferencePicker /><label className="block">Территория представительства<input name="territory" className="input-field" maxLength={160} /></label><div className="grid grid-cols-2 gap-3"><label>С даты<input name="starts_on" type="date" className="input-field" /></label><label>По дату<input name="ends_on" type="date" className="input-field" /></label></div><label className="block">Контакт представителя<input name="contact" className="input-field" maxLength={254} /></label><label className="block">Кто видит представителя<Visibility name="visibility" noContext /></label><label className="block">Кто видит контакт представителя<Visibility name="contact_visibility" /></label><button disabled={busy} className="btn-secondary">Добавить представителя</button></form></>}
  </section>;
}
function Visibility({ name, noContext = false }: { name: string; noContext?: boolean }) { return <select name={name} aria-label={name === 'visibility' ? 'Видимость' : 'Видимость контакта представителя'} className="input-field" defaultValue="private"><option value="private">Только я</option>{!noContext && <option value="work_context">В рабочем контексте</option>}<option value="members">Участники FilmVerse</option><option value="public">Публично</option></select>; }
