import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useRouter } from '../router';
import { useAuth } from '../hooks/useAuth';
import { useOrganization } from '../hooks/useOrganization';
import { useAuthModal } from '../components/AuthModal';
import { useSearchIndexing } from '../hooks/useSearchIndexing';
type Listing={id:string;title:string;description:string;city:string|null;format:string;price_type:string;price_amount:number|null;currency:string|null;starts_at?:string;ends_at?:string;duration_text?:string;category:string;registration_url:string|null;status:string};
const labels:Record<string,string>={online:'Онлайн',offline:'Очно',hybrid:'Гибрид',free:'Бесплатно',contact:'По запросу'};
export function IndustryListings({education=false,id,organizationId}:{education?:boolean;id?:string;organizationId?:string}){
 const {navigate}=useRouter();const {user}=useAuth();const {promptGuest}=useAuthModal();const {selected,can}=useOrganization();useSearchIndexing(false);
 const [rows,setRows]=useState<Listing[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [city,setCity]=useState('');const [format,setFormat]=useState('');const [price,setPrice]=useState('');const [page,setPage]=useState(0);const [revision,setRevision]=useState(0);
 const [creating,setCreating]=useState(false);const [owner,setOwner]=useState<{id:string;name:string}|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const table=education?'education_programs':'industry_events';
 useEffect(()=>{let stale=false;setRows([]);setLoading(true);setError('');const timer=setTimeout(()=>{void(async()=>{try{
 let query=supabase.from(table).select(education?'id,title,description,city,format,price_type,price_amount,currency,duration_text,category,registration_url,status':'id,title,description,city,format,price_type,price_amount,currency,starts_at,ends_at,category,registration_url,status').eq('status','published');
 if(id)query=query.eq('id',id);else{if(city)query=query.ilike('city','%'+city.trim()+'%');if(format)query=query.eq('format',format);if(price)query=query.eq('price_type',price);}
 if(organizationId)query=query.eq('organization_id',organizationId);
 const r=await query.order(education?'created_at':'starts_at',{ascending:!education}).range(page*24,page*24+23);if(r.error)throw r.error;if(!stale)setRows((r.data||[]) as unknown as Listing[]);
 }catch{if(!stale)setError('Не удалось загрузить публикации.');}finally{if(!stale)setLoading(false);}})();},200);return()=>{stale=true;clearTimeout(timer);};},[table,education,id,organizationId,city,format,price,page,revision]);
 const startCreate=()=>{if(!user){promptGuest({message:'Войдите, чтобы разместить публикацию.'});return;}if(education&&(!selected||selected.organization_type!=='education'||!can('manage_organization'))){setNotice('Для программы выберите киношколу в контексте компании. Нужны права управления организацией.');return;}if(selected&&!can('manage_organization')){setNotice('В выбранной компании нет прав на публикацию.');return;}setOwner(selected?{id:selected.id,name:selected.name}:null);setCreating(true);setNotice('');};
 return <section className="p-4 sm:p-8 space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><p className="text-emerald-500">Индустрия</p><h1 className="text-3xl font-display">{education?'Обучение':'События'}</h1></div>{!id&&<button className="btn-primary" onClick={startCreate}>{education?'Добавить программу':'Добавить событие'}</button>}</header>
 {education&&!id&&<button className="btn-secondary" onClick={()=>navigate('/companies')}>Найти киношколу</button>}
 {!id&&<div className="grid sm:grid-cols-3 gap-3"><input className="input-field" aria-label="Город публикации" placeholder="Город" value={city} onChange={e=>{setCity(e.target.value);setPage(0);}}/><select className="input-field" aria-label="Формат публикации" value={format} onChange={e=>{setFormat(e.target.value);setPage(0);}}><option value="">Любой формат</option>{['online','offline','hybrid'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select><select className="input-field" aria-label="Стоимость" value={price} onChange={e=>{setPrice(e.target.value);setPage(0);}}><option value="">Любая стоимость</option><option value="free">Бесплатно</option><option value="paid">Платно</option><option value="contact">По запросу</option></select></div>}
 {notice&&<p role="status">{notice}</p>}
 {creating&&<form className="surface p-5 grid sm:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setError('');void(async()=>{try{
 const common={title:String(data.get('title')),description:String(data.get('description')),city:String(data.get('city')),format:String(data.get('format')),category:String(data.get('category')),price_type:String(data.get('price_type')),price_amount:data.get('amount')?Number(data.get('amount')):null,currency:data.get('amount')?String(data.get('currency')):null,registration_url:String(data.get('url'))||null,status:'published',visibility:'public'};
 const payload=education?{...common,organization_id:owner?.id,program_type:String(data.get('kind')),duration_text:String(data.get('duration'))}:{...common,organizer_type:owner?'organization':'user',organization_id:owner?.id||null,user_id:owner?null:user?.id,event_type:String(data.get('kind')),starts_at:new Date(String(data.get('start'))).toISOString(),ends_at:new Date(String(data.get('end'))).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone};
 const r=await supabase.from(table).insert(payload).select('id').single();if(r.error)throw r.error;setCreating(false);setNotice('Публикация сохранена.');setRevision(v=>v+1);
 }catch{setError('Не удалось сохранить. Проверьте даты, стоимость и права публикации.');}finally{setBusy(false);}})();}}>
 <p className="sm:col-span-2">Публикует: {owner?.name||'Личный профиль'}. Стандартное размещение бесплатно; это не верификация.</p>
 <label>Название<input className="input-field" name="title" minLength={2} maxLength={180} required/></label><label>Категория<input className="input-field" name="category" maxLength={100}/></label>
 <label>Тип<select className="input-field" name="kind">{(education?['course','degree','intensive','masterclass','workshop','lab','webinar','lecture','certification','other']:['masterclass','workshop','lecture','webinar','screening','premiere','festival','networking','open_day','pitching','conference','expo','competition','meetup','other']).map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Формат<select className="input-field" name="format">{['online','offline','hybrid'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><label>Город<input className="input-field" name="city" maxLength={100}/></label>
 {education?<label>Продолжительность<input className="input-field" name="duration" maxLength={200}/></label>:<><label>Начало (ваш часовой пояс)<input className="input-field" name="start" type="datetime-local" required/></label><label>Окончание<input className="input-field" name="end" type="datetime-local" required/></label></>}
 <label>Стоимость<select className="input-field" name="price_type"><option value="free">Бесплатно</option><option value="paid">Платно</option><option value="contact">По запросу</option></select></label><label>Цена<input className="input-field" name="amount" type="number" min={0} step="0.01"/></label><label>Валюта<input className="input-field" name="currency" defaultValue="RUB" pattern="[A-Z]{3}" maxLength={3}/></label><label>HTTPS-ссылка регистрации<input className="input-field" name="url" type="url" pattern="https://.*"/></label>
 <label className="sm:col-span-2">Описание<textarea className="input-field" name="description" maxLength={10000}/></label><button className="btn-primary" disabled={busy}>Опубликовать</button><button type="button" className="btn-secondary" disabled={busy} onClick={()=>setCreating(false)}>Отмена</button></form>}
 {loading&&<p role="status">Загружаем публикации…</p>}{error&&<p role="alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Повторить</button></p>}{!loading&&!error&&!rows.length&&<p>Публичных публикаций по этим условиям пока нет.</p>}
 <div className={id?'space-y-4':'grid sm:grid-cols-2 xl:grid-cols-3 gap-4'}>{rows.map(row=><article key={row.id} className="surface p-5 space-y-3">{row.starts_at&&<p className="text-emerald-500">{new Date(row.starts_at).toLocaleString('ru-RU')}</p>}<h2 className="text-xl">{row.title}</h2><p>{row.city} · {labels[row.format]} · {row.price_type==='paid'?row.price_amount+' '+row.currency:labels[row.price_type]}</p><p className={id?'whitespace-pre-wrap':'line-clamp-3 text-txt-secondary'}>{row.description}</p>{!id?<button onClick={()=>navigate((education?'/education/':'/events/')+row.id)}>Подробнее</button>:row.registration_url?.startsWith('https://')&&<a className="btn-primary inline-block" href={row.registration_url} target="_blank" rel="noopener noreferrer">Регистрация у организатора ↗</a>}<button className="block text-sm text-emerald-500" onClick={()=>{void navigator.clipboard.writeText(location.origin+location.pathname+'#'+(education?'/education/':'/events/')+row.id).then(()=>setNotice('Ссылка скопирована.'),()=>setNotice('Не удалось скопировать ссылку.'));}}>Поделиться</button></article>)}</div>
 {!id&&<div className="flex gap-4"><button disabled={!page||loading} onClick={()=>setPage(v=>v-1)}>Назад</button><span>{page+1}</span><button disabled={rows.length<24||loading} onClick={()=>setPage(v=>v+1)}>Далее</button></div>}</section>;
}
