import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useRouter } from '../router';
import { modelCategories, modelMeasurements } from '../lib/modelTaxonomy';
import { useAuth } from '../hooks/useAuth';
import { StudentBadge } from '../components/StudentEducation';
import { ProfileMedia } from '../components/profile/ProfileMedia';
import { ProfileContacts } from '../components/profile/ProfileContacts';
import { MessageButton } from '../components/MessageButton';
type Model = { categories: string[]; bio: string; travel_ready: boolean; availability: string; paid_work: boolean; tfp_collaboration: boolean };
type Measures = Record<string, string | number | null>;
type Card = Model & { id: string; full_name: string; avatar_url: string | null; city: string | null; height_cm: number | null };
const emptyModel: Model = { categories: [], bio: '', travel_ready: false, availability: '', paid_work: true, tfp_collaboration: false };
export function ModelsPage() {
  const { navigate } = useRouter(); const { user } = useAuth();
  const [filters, setFilters] = useState<Record<string, string | boolean>>({}); const [page, setPage] = useState(0);
  const [rows, setRows] = useState<Card[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const change = (key: string, value: string | boolean) => { setFilters(f => ({ ...f, [key]: value })); setPage(0); };
  useEffect(() => { let stale = false; setLoading(true); setError(''); setRows([]);
    const timer = setTimeout(() => { void (async () => { try { const r = await supabase.rpc('model_search', { p_filters: filters, p_offset: page * 24 }); if (r.error) throw r.error; if (!stale) setRows(r.data || []); } catch { if (!stale) setError('Не удалось найти модели. Измените фильтры или повторите позже.'); } finally { if (!stale) setLoading(false); } })(); }, 250);
    return () => { stale = true; clearTimeout(timer); };
  }, [filters, page]);
  return <section className="p-4 sm:p-8 space-y-5"><header className="flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-display">Модели</h1>{user && <button className="btn-secondary" onClick={() => navigate('/model-settings')}>Моя модельная специализация</button>}</header>
    <p className="text-txt-secondary">Профессиональное портфолио, digitals и условия сотрудничества. Без оценок внешности.</p>
    <div className="grid sm:grid-cols-3 gap-3"><input aria-label="Город модели" placeholder="Город" className="input-field" onChange={e => change('city', e.target.value)} /><select aria-label="Категория модели" className="input-field" onChange={e => change('category', e.target.value)}><option value="">Все категории</option>{Object.entries(modelCategories).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select><input aria-label="Доступность модели" className="input-field" placeholder="Доступность" onChange={e => change('availability', e.target.value)} /></div>
    <details><summary className="cursor-pointer">Профессиональные параметры</summary><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-3">{[['height_min','Рост от, см'],['height_max','Рост до, см'],['hair','Цвет волос'],['eyes','Цвет глаз']].map(([k,label]) => <label key={k}>{label}<input className="input-field" type={k.startsWith('height') ? 'number' : 'text'} onChange={e => change(k,e.target.value)} /></label>)}</div><div className="flex flex-wrap gap-4 mt-3">{[['travel','Готовность к поездкам'],['digitals','Есть доступные digitals'],['portfolio','Есть доступное портфолио'],['represented','Есть представительство'],['verified','Личность подтверждена']].map(([k,label]) => <label key={k}><input type="checkbox" onChange={e => change(k,e.target.checked)} /> {label}</label>)}</div></details>
    {loading && <p role="status">Ищем модели…</p>}{error && <p role="alert">{error}</p>}{!loading && !error && !rows.length && <p>Модели с такими условиями не найдены.</p>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{rows.map(row => <button key={row.id} className="surface overflow-hidden text-left" onClick={() => navigate('/model/' + row.id)}>{row.avatar_url ? <img className="w-full aspect-[3/4] object-cover" src={row.avatar_url} alt={row.full_name} loading="lazy" /> : <div className="aspect-[3/4] bg-surface-700 flex items-center justify-center text-txt-muted">Портрет не добавлен</div>}<div className="p-4 space-y-2"><h2 className="font-semibold">{row.full_name}</h2><p>{row.city}{row.height_cm ? ` · ${row.height_cm} см` : ''}</p><p className="text-xs">{row.categories.map(k => modelCategories[k]).join(' · ')}</p></div></button>)}</div>
    <div className="flex gap-4"><button disabled={!page || loading} onClick={() => setPage(n=>n-1)}>Назад</button><span>Страница {page+1}</span><button disabled={rows.length<24 || loading} onClick={() => setPage(n=>n+1)}>Далее</button></div>
  </section>;
}
export function ModelPage({ id, editable = false }: { id: string; editable?: boolean }) {
  const { user } = useAuth(); const { navigate } = useRouter();
  const [person, setPerson] = useState<{ full_name: string; city: string | null; avatar_url: string | null } | null>(null);
  const [model, setModel] = useState<Model>(emptyModel); const [measures, setMeasures] = useState<Measures>({ visibility: 'private' });
  const [exists, setExists] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [credits, setCredits] = useState<{ id: string; title: string; kind: string; client_name: string | null; year: number | null }[]>([]); const [revision, setRevision] = useState(0);
  const owner = editable && user?.id === id;
  useEffect(() => { let stale=false; setLoading(true); setError(''); void (async()=>{ try {
    const [p,m,z,c]=await Promise.all([supabase.from('profiles').select('full_name,city,avatar_url').eq('id',id).maybeSingle(),supabase.from('model_profiles').select('categories,bio,travel_ready,availability,paid_work,tfp_collaboration').eq('user_id',id).maybeSingle(),supabase.from('model_measurements').select('height_cm,chest_cm,waist_cm,hips_cm,inseam_cm,shoe_eu,clothing_size,hair_color,hair_length,eye_color,visibility').eq('user_id',id).maybeSingle(),supabase.from('model_credits').select('id,title,kind,client_name,year').eq('user_id',id).order('year',{ascending:false}).limit(50)]);
    if([p,m,z,c].some(r=>r.error))throw new Error('load'); if(!stale){setPerson(p.data);setExists(!!m.data);setModel(m.data||emptyModel);setMeasures(z.data||{visibility:'private'});setCredits(c.data||[]);}
  } catch {if(!stale)setError('Не удалось загрузить модельную специализацию.');}finally{if(!stale)setLoading(false);} })();return()=>{stale=true;};},[id,revision]);
  if(loading)return <p role="status" className="p-8">Загружаем модельную специализацию…</p>;
  if(error)return <p role="alert" className="p-8">{error} <button onClick={()=>setRevision(n=>n+1)}>Повторить</button></p>;
  if(!person || (!owner && !exists))return <p className="p-8">Модельная специализация недоступна.</p>;
  return <section className="max-w-4xl mx-auto p-4 sm:p-8 space-y-5"><h1 className="text-3xl font-display">{owner?'Моя модельная специализация':person.full_name}</h1>{!owner && person.avatar_url && <img src={person.avatar_url} alt={person.full_name} className="w-48 aspect-[3/4] object-cover rounded-xl"/>}<p>{person.city}</p><StudentBadge userId={id} />
    {notice && <p role={notice.startsWith('Не ') ? 'alert' : 'status'}>{notice}</p>}
    {owner ? <form className="surface p-5 space-y-4" onSubmit={e=>{e.preventDefault();setBusy(true);setNotice('');void(async()=>{try{const r=await supabase.rpc('model_save',{p_model:model,p_measurements:measures});if(r.error)throw r.error;setExists(true);setNotice('Модельная специализация и параметры сохранены.');}catch{setNotice('Не сохранено. Проверьте параметры и соединение.');}finally{setBusy(false);}})();}}>
      <p className="text-txt-secondary">Это расширение вашего профиля, не новый аккаунт. Актёрскую и другие профессии можно сохранить.</p>
      <fieldset><legend>Категории — можно несколько</legend><div className="flex flex-wrap gap-3 mt-2">{Object.entries(modelCategories).map(([k,v])=><label key={k}><input type="checkbox" checked={model.categories.includes(k)} onChange={e=>setModel({...model,categories:e.target.checked?[...model.categories,k]:model.categories.filter(x=>x!==k)})} /> {v}</label>)}</div></fieldset>
      <label className="block">О модельной работе<textarea className="input-field w-full" value={model.bio} maxLength={5000} onChange={e=>setModel({...model,bio:e.target.value})} /></label>
      <label className="block">Доступность<input className="input-field w-full" value={model.availability} maxLength={200} onChange={e=>setModel({...model,availability:e.target.value})} /></label>
      <div className="flex flex-wrap gap-4">{[['paid_work','Оплачиваемая работа'],['tfp_collaboration','TFP / портфолио без оплаты'],['travel_ready','Готовность к поездкам']].map(([k,v])=><label key={k}><input type="checkbox" checked={Boolean(model[k as keyof Model])} onChange={e=>setModel({...model,[k]:e.target.checked})} /> {v}</label>)}</div>
      <div className="grid sm:grid-cols-3 gap-3">{Object.entries(modelMeasurements).map(([k,v])=><label key={k}>{v}<input className="input-field" type="number" step="0.5" value={measures[k]??''} onChange={e=>setMeasures({...measures,[k]:e.target.value})} /></label>)}{[['clothing_size','Размер одежды'],['hair_color','Цвет волос'],['hair_length','Длина волос'],['eye_color','Цвет глаз']].map(([k,v])=><label key={k}>{v}<input className="input-field" maxLength={40} value={measures[k]??''} onChange={e=>setMeasures({...measures,[k]:e.target.value})} /></label>)}</div>
      <label className="block">Видимость параметров<select className="input-field" value={measures.visibility||'private'} onChange={e=>setMeasures({...measures,visibility:e.target.value})}><option value="private">Только я</option><option value="work_context">Рабочий контекст</option><option value="members">Участники FilmVerse</option><option value="public">Публично</option></select></label>
      <button className="btn-primary" disabled={busy}>Сохранить специализацию</button>{exists && <button type="button" className="btn-secondary ml-3" onClick={()=>navigate('/model/'+id)}>Открыть страницу модели</button>}
    </form> : <div className="surface p-5 space-y-3"><p>{model.categories.map(k=>modelCategories[k]).join(' · ')}</p><p>{model.bio}</p><p>{model.availability}</p><p>{model.travel_ready?'Готовность к поездкам':'Поездки не указаны'}</p><p>{model.paid_work?'Оплачиваемая работа':''}{model.tfp_collaboration?' · TFP / портфолио — без оплаты':''}</p><dl className="grid grid-cols-2 gap-2">{Object.entries({...modelMeasurements,clothing_size:'Размер одежды',hair_color:'Цвет волос',hair_length:'Длина волос',eye_color:'Цвет глаз'}).filter(([k])=>measures[k]!=null).map(([k,v])=><div key={k}><dt className="text-txt-muted">{v}</dt><dd>{measures[k]}</dd></div>)}</dl><MessageButton targetUserId={id} /></div>}
    {exists && <><p className="text-sm text-txt-secondary">Digitals — естественные фотографии анфас, в профиль и в полный рост. Дорогая фотосессия не требуется. Они отделены от обработанного портфолио.</p><ProfileMedia userId={id} editable={owner} /><ProfileContacts userId={id} editable={owner} />
    <section className="surface p-5 space-y-3"><h2 className="font-semibold">Модельные работы</h2>{credits.map(c=><div key={c.id}>{c.title} · {c.kind} · {c.client_name} · {c.year}{owner && <button className="ml-3 text-danger-600" onClick={()=>{void(async()=>{const r=await supabase.from('model_credits').delete().eq('id',c.id).select('id').single();if(r.error)setNotice('Не удалось удалить работу.');else setRevision(n=>n+1);})();}}>Удалить</button>}</div>)}{owner && <form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);setBusy(true);void(async()=>{try{const r=await supabase.from('model_credits').insert({kind:d.get('kind'),title:d.get('title'),client_name:d.get('client'),year:Number(d.get('year'))||null}).select('id').single();if(r.error)throw r.error;form.reset();setRevision(n=>n+1);}catch{setNotice('Не удалось сохранить работу.');}finally{setBusy(false);}})();}}><input name="title" aria-label="Название модельной работы" className="input-field" required minLength={2} maxLength={200} placeholder="Название работы" /><select name="kind" aria-label="Тип модельной работы" className="input-field">{['campaign','editorial','lookbook','runway','ecommerce','commercial','catalog','other'].map(k=><option key={k}>{k}</option>)}</select><input name="client" className="input-field" placeholder="Клиент" maxLength={160} /><input name="year" type="number" min={1900} max={2200} className="input-field" placeholder="Год" /><button className="btn-secondary" disabled={busy}>Добавить работу</button></form>}</section></>}
  </section>;
}
