import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { useOrganization } from '../hooks/useOrganization';
type Dashboard={signups:number;qualified:number;rewards:{reward_type:string;approved_credits:number}[]};
export function PartnerCenter(){
 const {user}=useAuth();const {selected}=useOrganization();const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [codes,setCodes]=useState<{code:string;status:string}[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{let stale=false;setDashboard(null);setCodes([]);setError('');setLoading(true);void(async()=>{try{
 let q=supabase.from('growth_partners').select('id');q=selected?q.eq('organization_id',selected.id):q.eq('user_id',user?.id||'');const p=await q.maybeSingle();if(p.error)throw p.error;if(!p.data)return;
 const [d,c]=await Promise.all([supabase.rpc('referral_dashboard',{p_partner:p.data.id}),supabase.from('referral_campaigns').select('id').eq('partner_id',p.data.id).limit(100)]);if(d.error||c.error)throw d.error||c.error;
 const k=c.data?.length?await supabase.from('referral_codes').select('code,status').in('campaign_id',c.data.map(x=>x.id)).limit(100):{data:[],error:null};if(k.error)throw k.error;if(!stale){setDashboard(d.data);setCodes(k.data||[]);}
 }catch{if(!stale)setError('Не удалось загрузить партнёрский кабинет.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[selected,user]);
 return <section className="p-4 sm:p-8 space-y-5"><h1 className="text-3xl font-display">Партнёрский кабинет</h1><p>{selected?.name||'Личный контекст'}. Партнёрство не подтверждает профессиональные права или статус студента.</p>{loading&&<p role="status">Загружаем кабинет…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!loading&&!error&&!dashboard&&<p>В этом контексте нет доступной партнёрской программы. Самостоятельное подключение пока не открыто.</p>}{dashboard&&<><dl className="grid sm:grid-cols-2 gap-3"><div className="surface p-4"><dt>Регистрации с атрибуцией</dt><dd>{dashboard.signups}</dd></div><div className="surface p-4"><dt>Подтверждённые активации</dt><dd>{dashboard.qualified}</dd></div></dl><section className="surface p-5 space-y-3"><h2>Реферальные ссылки</h2>{codes.map(c=><div key={c.code}><code className="break-all">{c.code}</code><p>{c.status==='active'?'Ссылка активна':'Ссылка отключена'}</p><button disabled={c.status!=='active'} onClick={()=>{void navigator.clipboard.writeText(location.origin+location.pathname+'#/r/'+c.code).then(()=>setNotice('Ссылка скопирована.'),()=>setNotice('Не удалось скопировать ссылку.'));}}>Копировать</button></div>)}{!codes.length&&<p>Ссылки ещё не созданы.</p>}</section><section className="surface p-5 space-y-3"><h2>Подтверждённые вознаграждения</h2>{dashboard.rewards.map(r=><p key={r.reward_type}>{r.reward_type}: {r.approved_credits}</p>)}<p>Учёт подтверждений с учётом отмен. Выдача бонусов в AI/PRO ещё не подключена; это не доступный денежный баланс. Учёт кликов не включён.</p></section></>}</section>;
}
