import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { useOrganization } from '../hooks/useOrganization';
type Relation={id:string;user_id:string;organization_id:string;relationship_type:string;custom_role:string|null;status:string;public_on_organization_profile:boolean;public_on_professional_profile:boolean;organization_displays_relationship:boolean};
export function RelationshipsPage(){
 const {user}=useAuth();const {selected,can}=useOrganization();const [rows,setRows]=useState<Relation[]>([]);const [people,setPeople]=useState<{id:string;full_name:string}[]>([]);const [query,setQuery]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);const [notice,setNotice]=useState('');
 useEffect(()=>{let stale=false;setRows([]);setLoading(true);setError('');void(async()=>{try{let q=supabase.from('organization_professional_relationships').select('id,user_id,organization_id,relationship_type,custom_role,status,public_on_organization_profile,public_on_professional_profile,organization_displays_relationship').order('created_at',{ascending:false}).limit(100);q=selected?q.eq('organization_id',selected.id):q.eq('user_id',user?.id||'');const r=await q;if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Связи недоступны.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[selected,user,revision]);
 useEffect(()=>{let stale=false;setPeople([]);if(query.trim().length<2)return;const timer=setTimeout(()=>{void(async()=>{const r=await supabase.from('profiles').select('id,full_name').ilike('full_name','%'+query.trim()+'%').limit(12);if(!stale){if(r.error)setError('Поиск профилей недоступен.');else setPeople(r.data||[]);}})();},300);return()=>{stale=true;clearTimeout(timer);};},[query]);
 const action=async(id:string,choice:string,publicOrg=false,publicPerson=false)=>{setBusy(true);setError('');try{const r=await supabase.rpc('relationship_respond',{p_id:id,p_action:choice,p_public_org:publicOrg,p_public_person:publicPerson});if(r.error)throw r.error;setRevision(v=>v+1);setNotice('Решение сохранено.');}catch{setError('Решение не сохранено. Проверьте полномочия и статус связи.');}finally{setBusy(false);}};
 return <section className="p-4 sm:p-8 space-y-5"><h1 className="text-3xl font-display">Профессиональные связи</h1><p>{selected?'Контекст: '+selected.name:'Личный контекст'}. Это подтверждение сотрудничества, не верификация FilmVerse.</p>
 {selected&&can('manage_members')&&<form className="surface p-5 space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const org=selected.id;setBusy(true);setError('');void(async()=>{try{const r=await supabase.rpc('relationship_request',{p_org:org,p_person:d.get('person'),p_kind:d.get('kind'),p_role:String(d.get('role'))});if(r.error)throw r.error;setNotice('Запрос связи сохранён. Публикация возможна после подтверждения специалистом.');setRevision(v=>v+1);}catch{setError('Запрос не сохранён. Профиль может быть недоступен для приглашений.');}finally{setBusy(false);}})();}}><h2>Предложить сотрудничество</h2><input className="input-field" aria-label="Имя специалиста" placeholder="Найти по имени" value={query} onChange={e=>setQuery(e.target.value)}/><select name="person" aria-label="Специалист" className="input-field" required><option value="">Выберите специалиста</option>{people.filter(p=>p.id!==user?.id).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select name="kind" aria-label="Тип связи" className="input-field">{['staff','regular_freelancer','preferred_crew','technical_partner','vendor_partner','instructor','mentor','other'].map(k=><option key={k}>{k}</option>)}</select><input className="input-field" name="role" aria-label="Роль специалиста" placeholder="Роль" maxLength={120}/><button className="btn-primary" disabled={busy}>Предложить связь</button></form>}
 {loading&&<p role="status">Загружаем связи…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!loading&&!error&&!rows.length&&<p>Запросов и связей пока нет.</p>}
 {rows.map(r=><form key={r.id} className="surface p-5 space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action(r.id,'confirm',d.get('org')==='on',d.get('person')==='on');}}><h2>{r.custom_role||r.relationship_type}</h2><p>Статус: {r.status}</p>{r.status==='pending'||r.status==='active'?<>{r.user_id!==user?.id&&<label className="block"><input type="checkbox" name="org" defaultChecked={r.organization_displays_relationship}/> Показывать связь на странице компании при согласии специалиста</label>}{r.user_id===user?.id&&<><label className="block"><input type="checkbox" name="org" defaultChecked={r.public_on_organization_profile}/> Разрешаю показывать связь на странице компании</label><label className="block"><input type="checkbox" name="person" defaultChecked={r.public_on_professional_profile}/> Разрешаю показывать связь в моём профиле</label></>}<div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={busy}>Подтвердить связь</button><button className="btn-secondary" type="button" disabled={busy} onClick={()=>void action(r.id,r.status==='pending'?'decline':'end')}>{r.status==='pending'?'Отклонить':'Завершить связь'}</button></div></>:null}</form>)}</section>;
}
