import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useOrganization } from '../hooks/useOrganization';
import { useAuth } from '../hooks/useAuth';
import { useAuthModal } from '../components/AuthModal';
import { useRouter } from '../router';
import { StudentEducation, StudentReview, type Affiliation } from '../components/StudentEducation';
import { StudentSupportProgram } from '../components/StudentSupport';
import { ModalShell } from '../components/ModalShell';
import { compensationLabels } from '../lib/modelTaxonomy';

export function StudentsPage(){
 const {user}=useAuth();const {navigate}=useRouter();const {openLogin}=useAuthModal();const [creating,setCreating]=useState(false);
 const [projects,setProjects]=useState<{id:string;title:string}[]>([]);const [error,setError]=useState('');
 useEffect(()=>{let stale=false;if(!user)return;void(async()=>{const r=await supabase.from('projects').select('id,title').eq('user_id',user.id).is('organization_id',null).eq('student_project',true).order('created_at',{ascending:false}).limit(50);if(!stale){if(r.error)setError('Не удалось загрузить ваши учебные проекты.');else setProjects(r.data||[]);}})();return()=>{stale=true;};},[user]);
 return <section className="max-w-5xl mx-auto p-4 sm:p-8 space-y-6"><header className="surface p-6 space-y-4"><p className="text-emerald-500">Войти в индустрию через реальную работу</p><h1 className="text-3xl font-display">Студентам кино и продакшна</h1><p>Сохраните образование, подтвердите текущее обучение и представьте свой проект. Ищите актёров, моделей, специалистов и компании, которые открыто готовы помогать.</p><div className="flex flex-wrap gap-3"><button className="btn-primary" onClick={()=>user?setCreating(true):openLogin()}>Создать студенческий проект</button><button className="btn-secondary" onClick={()=>navigate('/student-projects')}>Студенческие проекты</button><button className="btn-secondary" onClick={()=>navigate('/student-support')}>Найти поддержку</button></div><p className="text-sm text-txt-muted">Пошаговый Crew Builder ещё не запущен. Сейчас доступны проект, самостоятельный поиск и структурированные запросы помощи для студенческих проектов. Подтверждение даёт более высокие лимиты.</p></header>
 {user&&<><StudentEducation userId={user.id} editable/><StudentSupportProgram editable/>{error&&<p role="alert">{error}</p>}<section className="surface p-5 space-y-3"><h2 className="font-semibold">Мои студенческие проекты</h2>{projects.length?projects.map(p=><button className="block text-emerald-500" key={p.id} onClick={()=>navigate('/project/'+p.id)}>{p.title}</button>):<p>Пока нет проектов.</p>}</section><StudentReview/></>}
 {creating&&<StudentProjectCreate onClose={()=>setCreating(false)} onSaved={id=>{setCreating(false);navigate('/project/'+id);}}/>}</section>;
}
function StudentProjectCreate({onClose,onSaved}:{onClose:()=>void;onSaved:(id:string)=>void}){
 const {user}=useAuth();const context=useOrganization();const [publisher]=useState(context.selected);const [affiliations,setAffiliations]=useState<Pick<Affiliation,'id'|'institution_name'>[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let stale=false;if(!user)return;void(async()=>{const r=await supabase.from('education_affiliations').select('id,institution_name').eq('user_id',user.id).limit(30);if(!stale){if(r.error)setError('Образование не загружено; можно создать проект без связи.');else setAffiliations(r.data||[]);}})();return()=>{stale=true;};},[user]);
 return <ModalShell title="Студенческий проект" onClose={()=>{if(!busy)onClose();}}><form className="space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');void(async()=>{try{const r=await supabase.from('projects').insert({organization_id:publisher?.id||null,title:d.get('title'),city:d.get('city'),genre:d.get('genre'),logline:d.get('logline'),description:d.get('description'),stage:'Разработка',student_project:true,thesis_project:d.get('thesis')==='on',education_affiliation_id:d.get('affiliation')||null,visibility:d.get('visibility'),shoot_start:d.get('start')||null,shoot_end:d.get('end')||null}).select('id').single();if(r.error)throw r.error;onSaved(r.data.id);}catch{setError('Проект не сохранён. Проверьте поля, даты и выбранное образование.');}finally{setBusy(false);}})();}}>
 <p className="text-sm text-txt-secondary">{publisher?`Публикуется от компании «${publisher.name}».`:'Публикуется от вашего личного профиля.'} «Студенческий проект» — ваше описание; подтверждённый бейдж зависит от действующего подтверждения связанного обучения.</p>
 {([['title','Название'],['city','Город'],['genre','Тип / формат'],['logline','Кратко о проекте']] as const).map(([k,v])=><label className="block" key={k}>{v}<input name={k} className="input-field w-full" required maxLength={200}/></label>)}<label className="block">Описание<textarea name="description" className="input-field w-full" maxLength={5000}/></label>
 <label className="block">Связанное образование<select name="affiliation" className="input-field w-full"><option value="">Без связи — самоописание проекта</option>{affiliations.map(a=><option key={a.id} value={a.id}>{a.institution_name}</option>)}</select></label><label><input name="thesis" type="checkbox"/> Дипломный проект</label>
 <div className="grid grid-cols-2 gap-3"><label>Начало съёмок<input type="date" name="start" className="input-field"/></label><label>Окончание съёмок<input type="date" name="end" className="input-field"/></label></div>
 <label className="block">Видимость проекта<select name="visibility" className="input-field" defaultValue="private"><option value="private">Приватный</option><option value="unlisted">По прямой ссылке</option><option value="public">Публичный</option></select></label>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={busy}>Сохранить студенческий проект</button></form></ModalShell>;
}
export function StudentProjectsPage(){
 const {navigate}=useRouter();const [filters,setFilters]=useState<Record<string,string|boolean>>({});const [page,setPage]=useState(0);const [rows,setRows]=useState<{id:string;title:string;city:string;logline:string;verified_student_project:boolean}[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let stale=false;setLoading(true);setRows([]);setError('');const timer=setTimeout(()=>{void(async()=>{try{const r=await supabase.rpc('student_project_search',{p_filters:filters,p_offset:page*24});if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Не удалось загрузить студенческие проекты.');}finally{if(!stale)setLoading(false);}})();},250);return()=>{stale=true;clearTimeout(timer);};},[filters,page]);
 const change=(k:string,v:string|boolean)=>{setFilters(f=>({...f,[k]:v}));setPage(0);};
 return <section className="p-4 sm:p-8 space-y-5"><h1 className="text-3xl font-display">Студенческие проекты</h1><p className="text-txt-secondary">Подтверждённый бейдж говорит только о связи с действующим обучением, не о безопасности или качестве производства.</p><div className="grid sm:grid-cols-3 gap-3">{[['city','Город'],['school','Публично указанная школа'],['genre','Тип / формат']].map(([k,v])=><input key={k} aria-label={v} placeholder={v} className="input-field" onChange={e=>change(k,e.target.value)}/>)}<label>Съёмки не раньше<input type="date" className="input-field" onChange={e=>change('from',e.target.value)}/></label><label><input type="checkbox" onChange={e=>change('verified',e.target.checked)}/> Подтверждённая связь с обучением</label></div><div className="grid sm:grid-cols-3 gap-3"><select className="input-field" aria-label="Потребность проекта" onChange={e=>change('need',e.target.value)}><option value="">Все потребности</option><option value="person">Команда</option><option value="equipment">Оборудование</option><option value="location">Локация</option><option value="mentorship">Консультация</option><option value="company">Компания</option></select><input className="input-field" aria-label="Цех проекта" placeholder="Цех" onChange={e=>change('department',e.target.value)}/><select className="input-field" aria-label="Условия помощи" onChange={e=>change('compensation',e.target.value)}><option value="">Все условия помощи</option>{Object.entries(compensationLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label><input type="checkbox" onChange={e=>change('cast',e.target.checked)}/> Открыт набор актёров / моделей</label></div>{loading&&<p role="status">Ищем проекты…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!rows.length&&<p>По этим условиям проектов нет.</p>}<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{rows.map(p=><button key={p.id} className="surface p-5 text-left space-y-2" onClick={()=>navigate('/project/'+p.id)}><h2 className="font-semibold">{p.title}</h2><p className="text-sky-400 text-sm">{p.verified_student_project?'Подтверждённый студенческий проект':'Студенческий проект — самоописание'}</p><p>{p.city}</p><p>{p.logline}</p></button>)}</div><div className="flex gap-4"><button disabled={!page||loading} onClick={()=>setPage(n=>n-1)}>Назад</button><span>Страница {page+1}</span><button disabled={rows.length<24||loading} onClick={()=>setPage(n=>n+1)}>Далее</button></div></section>;
}
export function StudentSupportPage(){
 const {navigate}=useRouter();const [kind,setKind]=useState('person');const [city,setCity]=useState('');const [type,setType]=useState('');const [page,setPage]=useState(0);
 const [rows,setRows]=useState<{id:string;name:string;slug:string;kind:string;description:string;terms:string;support_types:string[]}[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let stale=false;setLoading(true);setError('');setRows([]);const timer=setTimeout(()=>{void(async()=>{try{const r=await supabase.rpc('support_search',{p_kind:kind,p_city:city.trim(),p_type:type.trim(),p_offset:page*24});if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Не удалось найти поддержку.');}finally{if(!stale)setLoading(false);}})();},250);return()=>{stale=true;clearTimeout(timer);};},[kind,city,type,page]);
 return <section className="p-4 sm:p-8 space-y-5"><h1 className="text-3xl font-display">Поддержка студенческих проектов</h1><p>Здесь только добровольно включённые программы. Наличие программы не гарантирует бесплатную помощь. Свяжитесь через публичный профиль или сайт компании.</p><div className="grid sm:grid-cols-3 gap-3"><select aria-label="Кто помогает" className="input-field" value={kind} onChange={e=>{setKind(e.target.value);setPage(0);setType('');}}><option value="person">Люди</option><option value="company">Компании</option></select><input className="input-field" aria-label="Город поддержки" placeholder="Город" value={city} onChange={e=>{setCity(e.target.value);setPage(0);}}/><select className="input-field" aria-label="Тип поддержки" value={type} onChange={e=>{setType(e.target.value);setPage(0);}}><option value="">Любая поддержка</option><option value="mentorship">Наставничество</option><option value="equipment">Оборудование</option>{kind==='company'?<><option value="rental_discount">Скидка на аренду</option><option value="postproduction">Постпродакшн</option></>:<><option value="crew">Работа в группе</option><option value="tfp">TFP / портфолио</option></>}</select></div>{loading&&<p role="status">Ищем поддержку…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!rows.length&&<p>Открытые программы по этим условиям не найдены.</p>}{rows.map(r=><article className="surface p-5 space-y-2" key={r.id}><h2 className="font-semibold">{r.name}</h2><p className="text-amber-400">Поддерживает студентов</p><p>{r.description}</p><p>{r.terms}</p>{r.slug&&<button className="btn-secondary" onClick={()=>navigate((r.kind==='company'?'/company/':'/u/')+r.slug)}>Открыть профиль</button>}</article>)}<div className="flex gap-4"><button disabled={!page||loading} onClick={()=>setPage(n=>n-1)}>Назад</button><span>Страница {page+1}</span><button disabled={rows.length<24||loading} onClick={()=>setPage(n=>n+1)}>Далее</button></div></section>;
}
