import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
type Role={id:string;title:string};
type Candidate={id:string;casting_subject_id:string;status:string;project_tags:string[]};
const statuses:Record<string,string>={new:'Новый',review:'На рассмотрении',shortlist:'Шорт-лист',audition:'Пробы',hold:'Ожидание',approved:'Одобрен',backup:'Резерв',rejected:'Отклонён'};
export function CastingWorkspace({projectId}:{projectId:string}){
 const [notes,setNotes]=useState<{id:string;candidate_id:string;body:string;private:boolean}[]>([]);
 const [roles,setRoles]=useState<Role[]>([]);const [role,setRole]=useState('');const [candidates,setCandidates]=useState<Candidate[]>([]);const [applications,setApplications]=useState<{id:string;casting_subject_id:string}[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let stale=false;setError('');setLoading(true);void(async()=>{try{const r=await supabase.from('casting_roles').select('id,title').eq('project_id',projectId).order('created_at').limit(100);if(r.error)throw r.error;const w=await supabase.from('work_opportunities').select('id').eq('project_id',projectId).limit(100);if(w.error)throw w.error;const a=w.data?.length?await supabase.from('work_applications').select('id,casting_subject_id').in('work_id',w.data.map(x=>x.id)).eq('status','applied').limit(100):{data:[],error:null};if(a.error)throw a.error;if(!stale){setRoles(r.data||[]);setApplications(a.data||[]);}}catch{if(!stale)setError('Не удалось загрузить кастинг. Проверьте права проекта.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[projectId,revision]);
 useEffect(()=>{let stale=false;setCandidates([]);setNotes([]);if(!role)return;void(async()=>{const r=await supabase.from('role_candidates').select('id,casting_subject_id,status,project_tags').eq('role_id',role).order('created_at').limit(100);if(r.error){if(!stale)setError('Кандидаты недоступны.');return;}const ids=(r.data||[]).map(c=>c.id);const results=ids.length?await Promise.all([supabase.from('casting_reviewer_notes').select('id,candidate_id,body').in('candidate_id',ids).limit(100),supabase.from('casting_comments').select('id,candidate_id,body').in('candidate_id',ids).limit(100)]):[];if(!stale){setCandidates(r.data||[]);if(results.some(x=>x.error))setError('Не удалось загрузить заметки.');else setNotes(results.flatMap((x,i)=>(x.data||[]).map(n=>({...n,private:i===0}))));}})();return()=>{stale=true;};},[role,revision]);
 const mutate=async(action:()=>PromiseLike<{error:unknown}>)=>{setBusy(true);setError('');setNotice('');try{const r=await action();if(r.error)throw r.error;setRevision(v=>v+1);setNotice('Сохранено.');}catch{setError('Не удалось сохранить. Проверьте права, источник кандидата и согласие представителя.');}finally{setBusy(false);}};
 return <section className="surface p-5 space-y-4"><h2 className="text-xl">Кастинг проекта</h2><p className="text-sm text-txt-secondary">Роли → кандидаты → пробы → решение. Статус «Одобрен» не заключает договор и не добавляет человека в команду.</p>
 {loading&&<p role="status">Загружаем кастинг…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const title=String(new FormData(f).get('title'));void mutate(()=>supabase.from('casting_roles').insert({project_id:projectId,title}).select('id').single());}}><input className="input-field flex-1" name="title" aria-label="Название роли" placeholder="Название роли" minLength={2} maxLength={160} required/><button className="btn-secondary" disabled={busy}>Создать роль</button></form>
 <select className="input-field" aria-label="Роль кастинга" value={role} onChange={e=>setRole(e.target.value)}><option value="">Выберите роль</option>{roles.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select>
 {role&&<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const app=applications.find(a=>a.id===new FormData(e.currentTarget).get('application'));if(app)void mutate(()=>supabase.from('role_candidates').insert({role_id:role,casting_subject_id:app.casting_subject_id,application_id:app.id,source:'application'}).select('id').single());}}><select className="input-field flex-1" name="application" aria-label="Отклик для кастинга" required><option value="">Выберите отклик проекта</option>{applications.map(a=><option key={a.id} value={a.id}>Отклик {a.id.slice(0,8)}</option>)}</select><button className="btn-secondary" disabled={busy||!applications.length}>Добавить кандидата</button></form>}
 {role&&!candidates.length&&<p>В этой роли пока нет доступных кандидатов.</p>}
 {candidates.map(c=><article className="border border-line-soft rounded-xl p-4 space-y-3" key={c.id}><h3>Кандидат {c.id.slice(0,8)}</h3><select className="input-field" aria-label={'Статус кандидата '+c.id.slice(0,8)} value={c.status} disabled={busy} onChange={e=>{const status=e.target.value;void mutate(()=>supabase.from('role_candidates').update({status}).eq('id',c.id).select('id').single());}}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{notes.filter(n=>n.candidate_id===c.id).map(n=><p key={n.id} className="whitespace-pre-wrap text-sm"><span className="text-txt-muted">{n.private?'Личная заметка':'Команде'}: </span>{n.body}</p>)}<form className="space-y-2" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const d=new FormData(f);const privateNote=d.get('scope')==='private';void mutate(()=>supabase.from(privateNote?'casting_reviewer_notes':'casting_comments').insert({candidate_id:c.id,body:String(d.get('body'))}).select('id').single());}}><select name="scope" aria-label="Вид заметки" className="input-field"><option value="private">Личная заметка — только вам</option><option value="shared">Комментарий команде кастинга</option></select><textarea className="input-field" name="body" aria-label="Текст заметки" required maxLength={5000}/><button className="btn-secondary" disabled={busy}>Сохранить заметку</button></form></article>)}
 <p className="text-xs text-txt-muted">Отправка self-tape запросов и загрузка медиа ещё не включены. Детские запросы нельзя отправлять в обход представителя.</p></section>;
}
