import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { resolveNeed, type ProjectNeedTarget } from '../lib/projectNeed';
type Need={id:string;title:string;target_type:ProjectNeedTarget;resolution_route:string;status:string;quantity:number};
const targets:Record<ProjectNeedTarget,string>={person:'Специалист',casting_subject:'Актёр / модель',organization:'Компания',equipment:'Оборудование',package:'Комплект оборудования',location:'Локация',transport:'Транспорт',service:'Услуга',postproduction:'Постпродакшн',other:'Другое'};
const routes:Record<string,string>={professional_proposal:'Закрытое предложение специалиста',casting:'Кастинг',young_talent_casting:'Кастинг через представителя',equipment_sourcing:'Оборудование / тендер',company_rfp:'Запрос компании',provider_sourcing:'Поиск поставщика',manual:'Ручной подбор'};
export function ProjectNeeds({projectId}:{projectId:string}){
 const [rows,setRows]=useState<Need[]>([]);const [target,setTarget]=useState<ProjectNeedTarget>('person');const [minor,setMinor]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
 useEffect(()=>{let stale=false;setRows([]);setLoading(true);setError('');void(async()=>{try{const r=await supabase.from('project_needs').select('id,title,target_type,resolution_route,status,quantity').eq('project_id',projectId).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Потребности проекта недоступны.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[projectId,revision]);
 return <section className="surface p-5 space-y-4"><h2 className="text-xl">Потребности проекта</h2><p className="text-txt-secondary">Единая основа ручного подбора и будущего Production Agent. Создание потребности никого не приглашает и не бронирует.</p>{loading&&<p role="status">Загружаем потребности…</p>}{error&&<p role="alert">{error}</p>}
 <form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);setBusy(true);setError('');void(async()=>{try{const r=await supabase.from('project_needs').insert({project_id:projectId,title:String(d.get('title')),description:String(d.get('description')),target_type:target,resolution_route:resolveNeed(target,minor),quantity:Number(d.get('quantity'))}).select('id').single();if(r.error)throw r.error;form.reset();setRevision(v=>v+1);}catch{setError('Потребность не сохранена. Проверьте права проекта.');}finally{setBusy(false);}})();}}>
 <label>Что нужно<input className="input-field" name="title" required minLength={2} maxLength={180}/></label><label>Тип потребности<select className="input-field" value={target} onChange={e=>{setTarget(e.target.value as ProjectNeedTarget);setMinor(false);}}>{Object.entries(targets).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {target==='casting_subject'&&<label><input type="checkbox" checked={minor} onChange={e=>setMinor(e.target.checked)}/> Несовершеннолетний — только защищённый кастинг</label>}<label>Количество<input className="input-field" type="number" name="quantity" required min={1} max={100000} defaultValue={1}/></label><label className="sm:col-span-2">Требования<textarea className="input-field" name="description" maxLength={5000}/></label><p>Маршрут: {routes[resolveNeed(target,minor)]}</p><button className="btn-secondary" disabled={busy}>Сохранить потребность</button></form>
 {!loading&&!error&&!rows.length&&<p>Потребности пока не добавлены.</p>}<ul className="space-y-2">{rows.map(n=><li className="border border-line-soft rounded-lg p-3" key={n.id}><h3>{n.title} × {n.quantity}</h3><p>{targets[n.target_type]} · {routes[n.resolution_route]}</p><p className="text-sm text-txt-muted">{n.status}</p></li>)}</ul></section>;
}
