import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { useOrganization } from '../hooks/useOrganization';
import { ModalShell } from './ModalShell';
import { compensationLabels } from '../lib/modelTaxonomy';
const personTypes:Record<string,string>={mentorship:'Наставничество',crew:'Работа в группе',tfp:'TFP / портфолио',equipment:'Оборудование',remote_consultation:'Удалённая консультация',other:'Другое'};
const companyTypes:Record<string,string>={rental_discount:'Скидка на аренду',equipment:'Оборудование',location:'Локация',postproduction:'Постпродакшн',transport:'Транспорт',props:'Реквизит',costume:'Костюм',makeup:'Грим',studio:'Студия',mentorship:'Наставничество',production_service:'Продакшн',casting:'Кастинг',other:'Другое'};
const supportNeedTypes:Record<string,string>={person:'Человек / команда',company:'Компания / подрядчик',equipment:'Оборудование',location:'Локация',transport:'Транспорт',postproduction:'Постпродакшн',mentorship:'Наставничество',service:'Услуга',other:'Другое'};
type Program={enabled:boolean;support_types:string[];cities:string[];description:string;terms:string};
export function StudentSupportProgram({companyId,editable=false}:{companyId?:string;editable?:boolean}){
 const {user}=useAuth();const context=useOrganization();const id=companyId||user?.id;const table=companyId?'organization_student_support':'student_support_preferences';const key=companyId?'organization_id':'user_id';
 const canEdit=editable&&!!id&&(!companyId||context.can('manage_organization',companyId));
 const [row,setRow]=useState<Program>({enabled:false,support_types:[],cities:[],description:'',terms:''});const [exists,setExists]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const types=companyId?companyTypes:personTypes;
 useEffect(()=>{let stale=false;if(!id){setLoading(false);return;}setLoading(true);setError('');setNotice('');setRow({enabled:false,support_types:[],cities:[],description:'',terms:''});setExists(false);void(async()=>{try{const r=await supabase.from(table).select('enabled,support_types,cities,description,terms').eq(key,id).maybeSingle();if(r.error)throw r.error;if(!stale){setExists(!!r.data);if(r.data)setRow(r.data);}}catch{if(!stale)setError('Не удалось загрузить программу поддержки.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[id,table,key]);
 if(loading)return <p role="status">Загружаем программу поддержки…</p>;
 if(error&&!canEdit)return <p role="alert">{error}</p>;
 if(!canEdit)return row.enabled?<section className="surface p-5 space-y-2"><h2 className="text-amber-400 font-semibold">Поддерживает студентов</h2><p>{row.description}</p><p>{row.support_types.map(k=>types[k]||k).join(' · ')}</p><p>{row.terms}</p><p className="text-xs text-txt-muted">Добровольная программа, не верификация и не гарантия бесплатных услуг. Условия уточняются на сайте компании.</p></section>:null;
 return <section className="surface p-5 space-y-3"><h2 className="font-semibold">{companyId?'Программа поддержки студентов':'Готовность помогать студентам'}</h2>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<form className="space-y-3" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');setNotice('');void(async()=>{try{const r=await(exists?supabase.from(table).update(row).eq(key,id):supabase.from(table).insert({...row,[key]:id})).select(key).single();if(r.error)throw r.error;setExists(true);setNotice('Программа поддержки сохранена.');}catch{setError('Изменения не сохранены. Проверьте права и подключение.');}finally{setBusy(false);}})();}}>
 <label className="block"><input type="checkbox" checked={row.enabled} onChange={e=>setRow({...row,enabled:e.target.checked})}/> {companyId?'Публично поддерживаем студенческие проекты':'Хочу иногда помогать студенческим проектам'}</label><div className="flex flex-wrap gap-3">{Object.entries(types).map(([k,v])=><label key={k}><input type="checkbox" checked={row.support_types.includes(k)} onChange={e=>setRow({...row,support_types:e.target.checked?[...row.support_types,k]:row.support_types.filter(x=>x!==k)})}/> {v}</label>)}</div>
 <label className="block">Города через запятую<input className="input-field w-full" maxLength={1000} value={row.cities.join(',')} onChange={e=>setRow({...row,cities:e.target.value.split(',').map(x=>x.trim()).slice(0,20)})}/></label>
 <label className="block">Чем можете помочь<textarea className="input-field w-full" maxLength={2000} value={row.description} onChange={e=>setRow({...row,description:e.target.value})}/></label><label className="block">Условия и ограничения<textarea className="input-field w-full" maxLength={2000} value={row.terms} onChange={e=>setRow({...row,terms:e.target.value})}/></label><p className="text-xs text-txt-muted">По умолчанию выключено. Нет автоматических рассылок или обязательства принять запрос.</p><button className="btn-secondary" disabled={busy}>Сохранить программу поддержки</button></form></section>;
}
type Request={id:string;title:string;need_type:string;quantity:number;city:string;start_date:string;end_date:string;compensation_type:string;expenses_covered:string;usage_rights:string;deliverables:string;description:string;status:string;visibility:string};
export function ProjectSupport({projectId,verified,canManage}:{projectId:string;verified:boolean;canManage:boolean}){
 const {user}=useAuth();const [rows,setRows]=useState<Request[]>([]);const [error,setError]=useState('');const [creating,setCreating]=useState(false);const [revision,setRevision]=useState(0);const [loading,setLoading]=useState(true);
 useEffect(()=>{let stale=false;setLoading(true);setRows([]);setError('');void(async()=>{try{const r=await supabase.from('project_support_requests').select('id,title,need_type,quantity,city,start_date,end_date,compensation_type,expenses_covered,usage_rights,deliverables,description,status,visibility').eq('project_id',projectId).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Не удалось загрузить запросы помощи.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[projectId,revision]);
 return <section className="surface p-5 space-y-4"><h2 className="font-semibold text-xl">Потребности проекта</h2><p>Открытых запросов: {rows.filter(r=>r.status==='open').length}. Это запросы, не подтверждённые участники команды.</p>{canManage&&verified&&<button className="btn-primary" onClick={()=>setCreating(true)}>Попросить помощь</button>}{canManage&&!verified&&<p className="text-txt-muted">Для публикации запроса помощи подтвердите действующее обучение, связанное с проектом.</p>}{loading&&<p role="status">Загружаем запросы…</p>}{error&&<p role="alert">{error}</p>}
 {rows.map(r=><article className="border-t border-line-soft pt-3 space-y-2" key={r.id}><h3>{r.title} × {r.quantity}</h3><p>{supportNeedTypes[r.need_type]} · {r.city} · {r.start_date} — {r.end_date}</p><p className="font-semibold text-amber-400">{compensationLabels[r.compensation_type]}</p><p>{r.description}</p><p>Расходы: {r.expenses_covered}</p><p>Права использования: {r.usage_rights}</p><p>Результат: {r.deliverables}</p>{canManage&&r.status==='open'&&<button className="btn-secondary" onClick={()=>{void(async()=>{const result=await supabase.from('project_support_requests').update({status:'closed'}).eq('id',r.id).select('id').single();if(result.error)setError('Не удалось закрыть запрос.');else setRevision(n=>n+1);})();}}>Закрыть запрос</button>}{user&&!canManage&&<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const reason=new FormData(form).get('reason');void(async()=>{const result=await supabase.from('support_reports').insert({request_id:r.id,reason}).select('id').single();if(result.error)setError('Жалоба не сохранена или уже отправлена.');else{form.reset();setError('Жалоба сохранена для рассмотрения.');}})();}}><input name="reason" aria-label="Причина жалобы" className="input-field" required minLength={10} maxLength={2000} placeholder="Причина жалобы"/><button className="btn-secondary">Сообщить о нарушении</button></form>}</article>)}
 {creating&&<SupportRequestEditor projectId={projectId} onClose={()=>setCreating(false)} onSaved={()=>{setCreating(false);setRevision(n=>n+1);}}/>}</section>;
}
function SupportRequestEditor({projectId,onClose,onSaved}:{projectId:string;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [need,setNeed]=useState('person');
 const [department,setDepartment]=useState('');const [departments,setDepartments]=useState<{id:string;name:string}[]>([]);const [professions,setProfessions]=useState<{id:string;name:string}[]>([]);
 useEffect(()=>{let stale=false;void(async()=>{const r=await supabase.from('departments').select('id,name').order('name').limit(100);if(!stale){if(r.error)setError('Справочник цехов недоступен; можно описать потребность без привязки.');else setDepartments(r.data||[]);}})();return()=>{stale=true;};},[]);
 useEffect(()=>{let stale=false;setProfessions([]);if(!department)return;void(async()=>{const r=await supabase.from('professions').select('id,name').eq('department_id',department).order('name').limit(100);if(!stale){if(r.error)setError('Не удалось загрузить профессии цеха.');else setProfessions(r.data||[]);}})();return()=>{stale=true;};},[department]);
 return <ModalShell title="Структурированный запрос помощи" onClose={()=>{if(!busy)onClose();}}><form className="space-y-3" onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');void(async()=>{try{const r=await supabase.rpc('support_request_create',{p_project:projectId,p_data:{...values,need_type:need,quantity:Number(values.quantity),remote:values.remote==='on',credit_offered:values.credit_offered==='on'}});if(r.error)throw r.error;onSaved();}catch{setError('Запрос не сохранён. Проверьте поля, полномочия, актуальность подтверждения студента и лимит запросов.');}finally{setBusy(false);}})();}}>
 <label className="block">Что нужно<select className="input-field" value={need} onChange={e=>setNeed(e.target.value)}>{Object.entries(supportNeedTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <div className="grid sm:grid-cols-2 gap-3"><label>Цех (необязательно)<select name="department_id" className="input-field" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Без привязки к цеху</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Профессия (необязательно)<select key={department} name="profession_id" className="input-field"><option value="">Без привязки к профессии</option>{professions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{need==='equipment'&&<label className="block">Категория оборудования<input name="inventory_category" className="input-field" maxLength={100}/></label>}
 <label className="block">Кто или что требуется<input name="title" className="input-field w-full" required minLength={2} maxLength={160} placeholder="Например: 1AC, камера или консультация продюсера"/></label><label className="block">Описание<textarea name="description" className="input-field w-full" maxLength={5000}/></label>
 <div className="grid grid-cols-2 gap-3"><label>Количество<input name="quantity" className="input-field" type="number" defaultValue={1} min={1} max={100} required/></label><label>Город<input name="city" className="input-field" required maxLength={100}/></label><label>Начало<input name="start_date" className="input-field" type="date" required/></label><label>Окончание<input name="end_date" className="input-field" type="date" required/></label></div>
 <label className="block">Компенсация<select name="compensation_type" className="input-field" required defaultValue=""><option value="" disabled>Выберите условия</option>{Object.entries(compensationLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {([['expenses_covered','Какие расходы покрываются'],['usage_rights','Права использования результата'],['deliverables','Ожидаемый результат']] as const).map(([k,v])=><label className="block" key={k}>{v}<textarea name={k} className="input-field w-full" required maxLength={k==='expenses_covered'?1000:2000}/></label>)}
 {need==='mentorship'&&<><label className="block">Тема консультации<input name="mentorship_topic" className="input-field" required maxLength={200}/></label><label className="block">Ожидаемая длительность, минут<input name="duration_minutes" className="input-field" type="number" min={1} max={1440} required/></label><label><input name="remote" type="checkbox"/> Удалённо</label></>}
 <label className="block"><input name="credit_offered" type="checkbox"/> Указание в титрах (не заменяет оплату)</label><label className="block">Видимость<select name="visibility" className="input-field" defaultValue="private"><option value="private">Только управление проектом</option><option value="members">Участники FilmVerse</option><option value="public">Публично</option></select></label><p className="text-xs text-txt-muted">Студенческий статус не отменяет применимые требования к труду. Условия согласуют участники. Запрос не рассылается компаниям автоматически.</p>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={busy}>Сохранить запрос помощи</button></form></ModalShell>;
}
