import { useEffect, useState } from 'react';
import { GraduationCap } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { ModalShell } from './ModalShell';
export type Affiliation = { id: string; organization_id: string | null; institution_name: string; program: string; specialization: string; start_year: number | null; expected_graduation_year: number | null; status: string; visibility: string; badge_visible: boolean };
const educationColumns='id,organization_id,institution_name,program,specialization,start_year,expected_graduation_year,status,visibility,badge_visible';
const educationStatus: Record<string,string>={current_student:'Студент',recent_graduate:'Недавний выпускник',alumni:'Выпускник'};
export function StudentBadge({ userId }: { userId: string }) {
  const [verified,setVerified]=useState(false);
  useEffect(()=>{let stale=false;setVerified(false);void(async()=>{const r=await supabase.rpc('student_badge',{p_user:userId});if(!stale)setVerified(!r.error && r.data===true);})();return()=>{stale=true;};},[userId]);
  return verified?<span className="inline-flex items-center gap-2 text-sm text-sky-400" title="Подтверждено действующее обучение, не профессиональные навыки или безопасность"><GraduationCap className="w-4 h-4" />Подтверждённый студент</span>:null;
}
export function StudentEducation({ userId, editable=false }: { userId: string; editable?: boolean }) {
  const {user}=useAuth();const owner=editable && user?.id===userId;
  const [rows,setRows]=useState<Affiliation[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
  const [editing,setEditing]=useState<Affiliation|null>(null);const [proofFor,setProofFor]=useState<string|null>(null);
  const [records,setRecords]=useState<{id:string;affiliation_id:string;status:string;valid_until:string|null}[]>([]);
  useEffect(()=>{let stale=false;setLoading(true);setError('');void(async()=>{try{
    const [a,v]=await Promise.all([supabase.from('education_affiliations').select(educationColumns).eq('user_id',userId).order('created_at',{ascending:false}).limit(30),owner?supabase.from('student_verification_status').select('id,affiliation_id,status,valid_until').eq('user_id',userId).order('created_at',{ascending:false}).limit(50):Promise.resolve({data:[],error:null})]);
    if(a.error||v.error)throw new Error('load');if(!stale){setRows(a.data||[]);setRecords(v.data||[]);}
  }catch{if(!stale)setError('Не удалось загрузить образование.');}finally{if(!stale)setLoading(false);}})();return()=>{stale=true;};},[userId,owner,revision]);
  return <section className="surface p-5 space-y-4"><h2 className="font-semibold text-xl">Образование</h2><StudentBadge key={revision} userId={userId}/>
    {loading&&<p role="status">Загружаем образование…</p>}{error&&<p role="alert">{error} <button onClick={()=>setRevision(n=>n+1)}>Повторить</button></p>}
    {rows.map(a=>{const v=records.find(r=>r.affiliation_id===a.id);return <article key={a.id} className="border-t border-line-soft py-3 space-y-2"><h3>{a.institution_name||'Образовательная организация'}</h3><p>{a.program} · {a.specialization} · {educationStatus[a.status]}{a.expected_graduation_year?` · ${a.expected_graduation_year}`:''}</p>{owner&&<><p className="text-xs text-txt-muted">{a.visibility} · {v?v.status==='approved'&&v.valid_until&&new Date(v.valid_until)<=new Date()?'Срок подтверждения истёк':`Заявка: ${v.status}${v.valid_until?` · до ${new Date(v.valid_until).toLocaleDateString('ru')}`:''}`:'Обучение пока не подтверждено'}</p><button className="btn-secondary" onClick={()=>setEditing(a)}>Редактировать образование</button>{a.status==='current_student'&&<button className="btn-secondary ml-2" onClick={()=>setProofFor(a.id)}>Подтвердить обучение</button>}</>}</article>;})}
    {owner&&<><p className="text-sm text-txt-muted">Подтверждение имеет срок действия и не оценивает мастерство. При изменении школы, программы или статуса нужна новая проверка. Документы не публикуются.</p><button className="btn-secondary" onClick={()=>setEditing({id:'',organization_id:null,institution_name:'',program:'',specialization:'',start_year:null,expected_graduation_year:null,status:'current_student',visibility:'private',badge_visible:false})}>Добавить образование</button></>}
    {editing&&<EducationEditor initial={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);setRevision(n=>n+1);}}/>}
    {proofFor&&<EnrollmentProof affiliationId={proofFor} userId={userId} onClose={()=>setProofFor(null)} onSaved={()=>{setProofFor(null);setRevision(n=>n+1);}}/>}
  </section>;
}
function EducationEditor({initial,onClose,onSaved}:{initial:Affiliation;onClose:()=>void;onSaved:()=>void}){
 const [draft,setDraft]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [schools,setSchools]=useState<{id:string;name:string}[]>([]);
 useEffect(()=>{let stale=false;const timer=setTimeout(()=>{void(async()=>{const r=await supabase.rpc('company_search',{p_query:draft.institution_name,p_type:'education',p_city:'',p_offset:0});if(!stale)setSchools(r.error?[]:r.data||[]);})();},250);return()=>{stale=true;clearTimeout(timer);};},[draft.institution_name]);
 return <ModalShell title="Образовательная связь" onClose={()=>{if(!busy)onClose();}}><form className="space-y-3" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');const {id,...values}=draft;void(async()=>{try{const r=await (id?supabase.from('education_affiliations').update(values).eq('id',id):supabase.from('education_affiliations').insert(values)).select('id').single();if(r.error)throw r.error;onSaved();}catch{setError('Не сохранено. Проверьте школу, годы и подключение.');}finally{setBusy(false);}})();}}>
 <label className="block">Учебное заведение<input className="input-field w-full" required minLength={2} maxLength={200} value={draft.institution_name} onChange={e=>setDraft({...draft,institution_name:e.target.value,organization_id:null})}/></label>
 <label className="block">Связать со школой в FilmVerse<select className="input-field w-full" value={draft.organization_id||''} onChange={e=>setDraft({...draft,organization_id:e.target.value||null})}><option value="">Своё название — без связи с организацией</option>{draft.organization_id&&!schools.some(s=>s.id===draft.organization_id)&&<option value={draft.organization_id}>Существующая связь со школой</option>}{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
 {(['program','specialization'] as const).map((k,i)=><label className="block" key={k}>{i?'Специализация':'Программа'}<input className="input-field w-full" maxLength={160} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <div className="grid grid-cols-2 gap-3">{(['start_year','expected_graduation_year'] as const).map((k,i)=><label key={k}>{i?'Ожидаемый год выпуска':'Год начала'}<input className="input-field" type="number" min={1900} max={2200} value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value?Number(e.target.value):null})}/></label>)}</div>
 <label className="block">Статус<select className="input-field" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(educationStatus).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label className="block">Кто видит школу<select className="input-field" value={draft.visibility} onChange={e=>setDraft({...draft,visibility:e.target.value})}><option value="private">Только я</option><option value="members">Участники</option><option value="public">Публично</option></select></label>
 <label className="block"><input type="checkbox" checked={draft.badge_visible} onChange={e=>setDraft({...draft,badge_visible:e.target.checked})}/> Показывать действующий бейдж без раскрытия школы</label>
 {error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={busy}>Сохранить образование</button></form></ModalShell>;
}
function EnrollmentProof({affiliationId,userId,onClose,onSaved}:{affiliationId:string;userId:string;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <ModalShell title="Подтверждение текущего обучения" onClose={()=>{if(!busy)onClose();}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();const file=new FormData(e.currentTarget).get('proof');if(!(file instanceof File)||!file.size||file.size>10*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(file.type)){setError('Нужен PDF, JPG или PNG до 10 МБ.');return;}setBusy(true);setError('');void(async()=>{const path=`${userId}/${crypto.randomUUID()}`;let uploaded=false;try{const upload=await supabase.storage.from('student-evidence').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;uploaded=true;const r=await supabase.rpc('student_verification_submit',{p_affiliation:affiliationId,p_path:path});if(r.error)throw r.error;onSaved();}catch{if(uploaded){try{await supabase.storage.from('student-evidence').remove([path]);}catch{/* A later retention job can clean unreferenced uploads. */}}setError('Отправка не подтверждена: обновите список заявок, прежде чем повторять.  Проверьте год выпуска и соединение.');}finally{setBusy(false);}})();}}>
 <p>Документ о действующем обучении увидит только уполномоченный проверяющий. Закройте лишние данные: номер документа, дату рождения, домашний адрес.</p><input name="proof" aria-label="Документ об обучении" type="file" accept="application/pdf,image/jpeg,image/png" required/>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={busy}>{busy?'Отправляем…':'Отправить на проверку'}</button></form></ModalShell>;
}
export function StudentReview(){
 const [allowed,setAllowed]=useState(false);const [rows,setRows]=useState<{id:string;institution_name:string;program:string;expected_graduation_year:number;evidence_path:string;user_id:string;full_name:string;public_slug:string;specialization:string;created_at:string}[]>([]);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);
 useEffect(()=>{let stale=false;void(async()=>{try{const check=await supabase.rpc('student_reviewer');if(check.error)throw check.error;if(!stale)setAllowed(check.data===true);if(check.data!==true)return;const r=await supabase.rpc('student_review_queue');if(r.error)throw r.error;if(!stale)setRows(r.data||[]);}catch{if(!stale)setError('Не удалось проверить очередь заявок.');}})();return()=>{stale=true;};},[revision]);
 if(!allowed)return error?<p role="alert">{error}</p>:null;
 return <section className="surface p-5 space-y-4"><h2 className="font-semibold">Проверка студентов — уполномоченному рецензенту</h2>{error&&<p role="alert">{error}</p>}{!rows.length&&<p>Нет заявок для проверки.</p>}{rows.map(r=><form key={r.id} className="border-t border-line-soft pt-3 space-y-3" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const until=String(form.get('until'));const reason=String(form.get('reason'));setBusy(true);void(async()=>{try{setError('');const result=await supabase.rpc('student_verification_decide',{p_id:r.id,p_approve:true,p_until:new Date(until+'T12:00:00Z').toISOString(),p_reason:reason});if(result.error)throw result.error;setRevision(n=>n+1);}catch{setError('Решение не подтверждено. Обновите очередь и проверьте срок (не более года и не позднее выпуска).');}finally{setBusy(false);}})();}}><p>{r.full_name||'Участник FilmVerse'} · {r.public_slug||r.user_id}</p><p>{r.institution_name} · {r.program} · {r.specialization} · выпуск {r.expected_graduation_year}</p><p>Подано: {new Date(r.created_at).toLocaleString('ru')}</p><label className="block">Причина решения<textarea name="reason" required minLength={3} maxLength={1000} className="input-field"/></label><button type="button" className="btn-secondary" onClick={()=>{void(async()=>{const signed=await supabase.storage.from('student-evidence').createSignedUrl(r.evidence_path,60);if(signed.error)setError('Документ недоступен.');else window.open(signed.data.signedUrl,'_blank','noopener,noreferrer');})();}}>Открыть документ на 60 секунд</button><label className="block">Подтвердить до<input name="until" className="input-field" type="date" required/></label><button className="btn-primary" disabled={busy}>Подтвердить обучение</button><button type="button" className="btn-secondary ml-2" disabled={busy} onClick={e=>{const reason=String(new FormData(e.currentTarget.closest('form')!).get('reason')||'');if(reason.trim().length<3){setError('Укажите причину решения.');return;}setBusy(true);void(async()=>{try{setError('');const result=await supabase.rpc('student_verification_decide',{p_id:r.id,p_approve:false,p_until:null,p_reason:reason});if(result.error)throw result.error;setRevision(n=>n+1);}catch{setError('Не удалось подтвердить отклонение заявки. Обновите очередь.');}finally{setBusy(false);}})();}}>Отклонить</button></form>)}</section>;
}
